platform: linux
image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet-sdk
inputs:
- name: "{{src_path}}"
  path: "build-src"
caches:
- name: "{{src_path}}-cache"
  path: "build-cache"
outputs:
- name: "{{bin_path}}"
  path: "build-bin"
template: "scripts/build.sh"
interpreter: "/bin/bash"
arguments:
  build_configuration: "{{build_configuration}}"
  product_name: "{{product_name}}"
