platform: linux
image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet-sdk
inputs:
- name: "{{src_path}}"
  path: "build-src"
caches:
- name: "{{src_path}}-cache"
  path: "build-cache"
template: "scripts/unit-test.sh"
interpreter: "/bin/bash"
