name: build-release

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Configure
        run: mkdir -p ${{ github.workspace }}/artifacts/binaries

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@2.21
        with:
          name: finbourne/uav
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # https://developer.github.com/v3/repos/releases/#get-a-release
          tags: "latest,${{ github.event.release.tag_name }}"

      - name: Build uav-darwin-amd64
        run: GOARCH=amd64 GOOS=darwin go build -o ${{ github.workspace }}/artifacts/binaries/uav-darwin-amd64 -v . 
      - name: Build uav-linux-amd64
        run: GOARCH=amd64 GOOS=linux go build -o ${{ github.workspace }}/artifacts/binaries/uav-linux-amd64 -v . 
      - name: Build uav-windows-amd64
        run: GOARCH=amd64 GOOS=windows go build -o ${{ github.workspace }}/artifacts/binaries/uav-windows-amd64.exe -v .

      - name: Testing
        run: |
              echo URL IS: ${{ github.event.release.upload_url }}, tag is: ${{ github.event.release.tag_name }}, full release event: ${{ github.event.release }}
              echo Name: ${{ github.event.release.name }}
              echo version name is: ${{ github.event.release.tag_name }}
              echo release title is: ${{ github.event.release.name }}
              echo release body is: ${{ github.event.release.body }}
              echo repository is: ${{ github.repository }}

      - uses: shogo82148/actions-upload-release-asset@v1.2.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-darwin-amd64
      - uses: shogo82148/actions-upload-release-asset@v1.2.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-linux-amd64
      - uses: shogo82148/actions-upload-release-asset@v1.2.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/binaries/uav-windows-amd64.exe
