name: Release

on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.15.0
        with:
          # If the PR has the label release:major, release:minor, or release:patch, this will override bump_version_scheme
          bump_version_scheme: norelease
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
  
  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.15.0
        with:
          bump_version_scheme: norelease
      - name: Check out the repo
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Dockerhub (semver)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: finbourne/uav:${{ steps.release.outputs.version }}
      - name: Push to Dockerhub (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: finbourne/uav:latest