name: Release

on: 
  push:
    branches:
      - master

jobs:

  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.15.0
        with:
          # If the PR has the label release:major, release:minor, or release:patch, this will override bump_version_scheme
          bump_version_scheme: release:patch

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@2.21
        with:
          name: finbourne/uav
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest,${{ steps.release.outputs.version }}"